# Variable & Automatic Gradient Calculation
- Tensor vs Variable
- Graph and Gradient

## 1.Import Required Libraries

In [3]:
import torch
from torch.autograd import Variable

## 2. Tensor vs Variable
### 1) Declaration

In [4]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[-6.7932e-01,  4.5822e-41,  1.7393e-37,  0.0000e+00],
        [ 1.3396e-38,  0.0000e+00,  4.0006e-14,  7.0820e+31],
        [ 7.5338e+28,  9.2210e-40,  1.8314e+25,  6.9768e+22]])

In [5]:
x_variable = Variable(x_tensor)
x_variable

tensor([[-6.7932e-01,  4.5822e-41,  1.7393e-37,  0.0000e+00],
        [ 1.3396e-38,  0.0000e+00,  4.0006e-14,  7.0820e+31],
        [ 7.5338e+28,  9.2210e-40,  1.8314e+25,  6.9768e+22]])

### 2) Variables of a Variable

In [6]:
# .data -> wrapped tensor 
x_variable.data

tensor([[-6.7932e-01,  4.5822e-41,  1.7393e-37,  0.0000e+00],
        [ 1.3396e-38,  0.0000e+00,  4.0006e-14,  7.0820e+31],
        [ 7.5338e+28,  9.2210e-40,  1.8314e+25,  6.9768e+22]])

In [7]:
# .grad -> gradient of the variable
print(x_variable.grad)

None


In [8]:
# .requires_grad -> whether variable requres gradient
print(x_variable.requires_grad)

x_variable = Variable(x_tensor,requires_grad=True)
x_variable.requires_grad

False


True

In [9]:
# .volatile -> inference mode with minimal memory usage
# single volatile variable makes whole graph not requiring gradient

x_variable = Variable(x_tensor,volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:4: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:5: UserWarning: volatile was removed (Variable.volatile is always False)


(None, False, False)

## 3. Graph & Variables

In [13]:
# create graph

x = Variable(torch.FloatTensor(3,4),requires_grad=True)
y = x**2 + 4*x
z = 2*y +3

x.requires_grad,y.requires_grad,z.requires_grad

(True, True, True)

In [14]:
# .backward(gradient,retain_graph,create_graph,retain_variables)
# compute gradient of current variable w.r.t. graph leaves

gradient = torch.FloatTensor(3,4)
z.backward(gradient)

print(x.grad)
y.grad,z.grad

tensor([[-3.5886,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])


(None, None)